[build]
  command = "pnpm build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "8.15.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm dev"
  port = 3000
